### PR TITLE
[FIX] Set-up container name so it does not matter where it is cloned

### PR DESCRIPTION
**Pull request by anibalsolon**
git clone https://github.com/brainlife/brainlife --recursive FOLDER

breaks the dev setup if the FOLDER is not `brainlife`. The container name gets by default set to `<FOLDER>_<service>_1`, which is then different than what's referenced in the services e.g. `brainlife_mongodb_1`

### CODE REVIEW

**Comment by soichih** [comment]
I ran into this issue also. 

Wouldn't it be better to add `export COMPOSE_PROJECT_NAME=brainlife` in dev.sh? I don't like that you have to hard code the _1 on every container..

**Comment by anibalsolon** [comment]
Yeah the `_1` is sad, but didn't want to change the underlying services for now. We could change them.

Using COMPOSE_PROJECT_NAME would be ok as well, I find it better to be explicit about the container names, instead of relying in different sources to assemble it.

**Comment by soichih** [comment]
Why do you have to specify network name? Can't we just use the default network?

**Comment by anibalsolon** [comment]
1. The same naming thing, being explicit etc
2. Configurability- I myself have services running on my machine, I'd prefer to keep things isolated
3. Be able to bridge the network if needed, more control
4. ([the reasons here](https://docs.docker.com/network/bridge/#differences-between-user-defined-bridges-and-the-default-bridge))

seems like some lines of code for a good resource, especially for a dev set-up

**Comment by anibalsolon** [comment]
Ok, no more networks there @soichih

**Comment by soichih** [comment]
1. being explicit is good, but not necessary in this case.
2. services are already isolated into separate bridge network - per
docker-compose
3. same as above.
4. docker-compose creates and uses a user-defined network already.

So I don't see a reason for explicitly creating your network. Once you add
unnecessary configurations, it makes it hard to remove them due to a fear
of breaking something that we don't quite understand. So I'd be cautious of
adding things just because.

**Pull request merged**
